[project]
name = "worker-client"
version = "0.1.0"
description = ""
authors = [
    {name = "Julien Dubost",email = "julien.dubost@planny.ch"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-redis (>=0.4.0,<0.5.0)",
    "ipython (>=9.6.0,<10.0.0)",
    "setuptools (>=80.9.0,<81.0.0)",
    "redis (>=7.0.1,<8.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "black (>=25.9.0,<26.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=9.0.1,<10.0.0)"
]

[tool.poetry]
packages = [{include = "worker_client", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
