MESSAGE_LOG_STREAM_KEY = "log_stream_key"
MESSAGE_JOB_OUTPUT_STREAM_KEY = "job_stream_key"
MESSAGE_PAYLOAD_KEY = "payload_key"

CONSUMER_VERSION_MAJOR = "CONSUMER_VERSION_MAJOR"
CONSUMER_VERSION_MINOR = "CONSUMER_VERSION_MINOR"

REDIS_CONSUMER_NAME = "REDIS_CONSUMER_NAME"
REDIS_HOST = "REDIS_HOST"
REDIS_USERNAME = "REDIS_USERNAME"
REDIS_PASSWORD = "REDIS_PASSWORD"
REDIS_DB = "REDIS_DB"
